#!/usr/bin/env python3
"""Generates src/testmap.inc: a hand-built 64x64 test sea for M1.
Tile IDs match defs.inc: DEEP=1 SHALLOW=2 SAND=3 GRASS=4 FOREST=5 MTN=6.
"""
import random

W = H = 64
DEEP, SHALLOW, SAND, GRASS, FOREST, MTN = 1, 2, 3, 4, 5, 6

random.seed(7)

# Blob centers: (cx, cy, strength) — strength ~ radius^2 of influence
CENTERS = [(40, 30, 130), (14, 12, 55), (52, 52, 45)]

land = [[0] * W for _ in range(H)]
for y in range(H):
    for x in range(W):
        p = 0
        for cx, cy, s in CENTERS:
            d2 = (x - cx) ** 2 + (y - cy) ** 2
            p = max(p, s - d2)
        land[y][x] = 1 if random.random() * 96 < p else 0

for _ in range(3):  # CA smoothing
    new = [[0] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            n = sum(
                land[yy][xx]
                for yy in range(max(0, y - 1), min(H, y + 2))
                for xx in range(max(0, x - 1), min(W, x + 2))
            )
            new[y][x] = 1 if n >= 5 else 0
    land = new

# sea border
for i in range(W):
    land[0][i] = land[H - 1][i] = land[i][0] = land[i][W - 1] = 0


def neighbors4(x, y):
    for dx, dy in ((0, -1), (0, 1), (-1, 0), (1, 0)):
        nx, ny = x + dx, y + dy
        if 0 <= nx < W and 0 <= ny < H:
            yield land[ny][nx]
        else:
            yield 0


random.seed(42)
tiles = [[DEEP] * W for _ in range(H)]
for y in range(H):
    for x in range(W):
        if land[y][x]:
            if any(v == 0 for v in neighbors4(x, y)):
                tiles[y][x] = SAND
            else:
                r = random.random()
                tiles[y][x] = MTN if r < 0.06 else (FOREST if r < 0.3 else GRASS)
        else:
            if any(v == 1 for v in neighbors4(x, y)):
                tiles[y][x] = SHALLOW

with open("src/testmap.inc", "w") as f:
    f.write("; Auto-generated by tools/gen_testmap.py — do not edit\n")
    for y in range(H):
        f.write("    db " + ",".join(str(t) for t in tiles[y]) + "\n")

print("wrote src/testmap.inc")
