; Super Game Boy border: each sea gets a day or night border, chosen by
; bit 0 of the folded seed (a pure function of the seed, like the world).
; Border art lives in ROMX banks 1-2 (generated by tools/png2sgb.py from
; res/sgb_day.png / res/sgb_night.png) and is beamed to the SNES with the
; SGB VRAM-transfer commands (pandocs: SGB VRAM Transfer, Command Border).
;
; Unlock requirements (cartridge header, set in main.asm): $0146 = $03 and
; $014B = $33. Detection: the boot ROM leaves C = $14 only on SGB/SGB2.

INCLUDE "hardware.inc"
INCLUDE "defs.inc"

SECTION "SGB WRAM", WRAM0
wSGBBank: db            ; ROM bank of the selected border
wSGBSrc:  dw            ; its tile data address (map/pal follow at fixed offsets)

SECTION "SGB", ROM0

; in: hl = 16-byte packet. Bit-banged over JOYP bits 4/5: start pulse,
; 128 data bits (LSB first; P14 low = 0, P15 low = 1), stop 0 bit.
; Pulses >= 5 M-cycles, spaces >= 15 M-cycles, per pandocs.
; Timing is nop-counted for NORMAL CPU speed: never call this with CGB
; double speed active — the SGB would see 2x-fast pulses and drop the packet.
SGBSendPacket:
    xor a
    ldh [rJOYP], a             ; start pulse: P14+P15 low
    nop
    nop
    nop
    ld a, $30
    ldh [rJOYP], a             ; idle
    ld b, 16
.byte
    ld e, [hl]
    inc hl
    ld c, 8
.bit
    ld a, $20                  ; P14 low = 0 bit
    rr e
    jr nc, .send
    ld a, $10                  ; P15 low = 1 bit
.send
    ldh [rJOYP], a
    nop
    nop
    nop
    ld a, $30
    ldh [rJOYP], a             ; idle high
    nop
    nop
    nop
    nop
    nop
    dec c
    jr nz, .bit
    dec b
    jr nz, .byte
    ld a, $20                  ; stop bit: 0
    ldh [rJOYP], a
    nop
    nop
    nop
    ld a, $30
    ldh [rJOYP], a
    ret

; in: b = frames to wait. LCD must be ON (polls LY).
SGBWaitVBlanks:
.out
    ldh a, [rLY]
    cp 144
    jr nc, .out
.in
    ldh a, [rLY]
    cp 144
    jr c, .in
    dec b
    jr nz, .out
    ret

; The SGB reads VRAM-transfer data out of the video signal: the BG map must
; display tiles $00-$FF in order ($00-$13 on the first row, $14-$27 next).
; LCD off. clobbers a, b, c, d, e, h, l
SGBFillSeqMap:
    ld hl, $9800
    xor a                      ; tile number (wraps mod 256)
    ld c, 14                   ; 14 rows x 20 = 280 >= 256
.row
    ld b, 20
.col
    ld [hli], a
    inc a
    dec b
    jr nz, .col
    ld de, 32 - 20
    add hl, de
    dec c
    jr nz, .row
    ret

; in: a = ROM bank, hl = source (ROMX), de = dest (VRAM), bc = count
; (must be a multiple of 8). LCD off. Unrolled 8x like CopyVRAM.
SGBCopyROMtoVRAM:
    ld [$2000], a              ; MBC5 ROM bank select
    srl b
    rr c
    srl b
    rr c
    srl b
    rr c                         ; bc = count / 8
.loop
    REPT 8
    ld a, [hli]
    ld [de], a
    inc de
    ENDR
    dec bc
    ld a, b
    or c
    jr nz, .loop
    ret

; out: hl = wSGBSrc, a = wSGBBank
SGBGetSrc:
    ld a, [wSGBSrc]
    ld l, a
    ld a, [wSGBSrc+1]
    ld h, a
    ld a, [wSGBBank]
    ret

; Beam the seed's border to the SGB. Entry: LCD on (a nice frame showing,
; it gets frozen). out: a = 1 and LCD OFF (VRAM trashed, game tiles
; reloaded) iff running on SGB and the border was sent; a = 0 and LCD
; untouched otherwise. Caller redraws its screen, then calls SGBUnfreeze.
SGBTransferBorder::
    ld a, [wIsSGB]
    cp $14                       ; $14 = SGB/SGB2 (boot ROM C value)
    jr z, .sgb
    xor a
    ret
.sgb
    ; day or night: bit 0 of the folded seed
    ld a, [wSeed16+1]
    and 1
    jr nz, .night
    ld a, BANK(sgb_day_tiles)
    ld hl, sgb_day_tiles
    jr .sel
.night
    ld a, BANK(sgb_night_tiles)
    ld hl, sgb_night_tiles
.sel
    ld [wSGBBank], a
    ld a, l
    ld [wSGBSrc], a
    ld a, h
    ld [wSGBSrc+1], a
    ; freeze the SGB display so the VRAM trashing stays invisible
    ld hl, SGB_PKT_MASK_FRZ
    call SGBSendPacket
    ld b, 4                      ; >= 60 ms between packets (pandocs)
    call SGBWaitVBlanks
    ; transfer setup: canonical BGP, no scroll, map shows tiles $00-$FF
    call WaitVBlankPoll
    xor a
    ldh [rLCDC], a
    ldh [rSCX], a
    ldh [rSCY], a
    ld a, $E4
    ldh [rBGP], a
    call SGBFillSeqMap
    ; --- CHR_TRN: border tiles $00-$7F ---
    call SGBGetSrc
    ld de, $8000
    ld bc, 4096
    call SGBCopyROMtoVRAM
    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BLOCK01
    ldh [rLCDC], a
    ld hl, SGB_PKT_CHR0
    call SGBSendPacket
    ld b, 6                      ; transfer runs through the 5th frame
    call SGBWaitVBlanks
    ; --- CHR_TRN: border tiles $80-$FF ---
    call WaitVBlankPoll
    xor a
    ldh [rLCDC], a
    call SGBGetSrc
    ld bc, 4096
    add hl, bc
    ld de, $8000
    ld bc, 4096
    call SGBCopyROMtoVRAM
    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BLOCK01
    ldh [rLCDC], a
    ld hl, SGB_PKT_CHR1
    call SGBSendPacket
    ld b, 6
    call SGBWaitVBlanks
    ; --- PCT_TRN: 32x28+1 map at $8000, palettes 4-6 at $8800 ---
    call WaitVBlankPoll
    xor a
    ldh [rLCDC], a
    call SGBGetSrc
    ld bc, 8192
    add hl, bc
    ld de, $8000
    ld bc, 1856
    call SGBCopyROMtoVRAM
    call SGBGetSrc
    ld bc, 8192 + 1856
    add hl, bc
    ld de, $8800
    ld bc, 96
    call SGBCopyROMtoVRAM
    ld a, LCDC_ON | LCDC_BG_ON | LCDC_BLOCK01
    ldh [rLCDC], a
    ld hl, SGB_PKT_PCT
    call SGBSendPacket
    ld b, 6
    call SGBWaitVBlanks
    ; done: LCD off, game tiles restored. Caller redraws + unfreezes.
    call WaitVBlankPoll
    xor a
    ldh [rLCDC], a
    call LoadTiles
    ld a, 1
    ret

; Unfreeze the SGB display after the post-transfer redraw. No-op off SGB.
SGBUnfreeze::
    ld a, [wIsSGB]
    cp $14
    ret nz
    ld hl, SGB_PKT_MASK_OFF
    jp SGBSendPacket

SECTION "SGB packets", ROM0
SGB_PKT_MASK_FRZ: db $B9, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ; MASK_EN freeze
SGB_PKT_MASK_OFF: db $B9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ; MASK_EN off
SGB_PKT_CHR0:     db $99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ; CHR_TRN tiles $00-$7F
SGB_PKT_CHR1:     db $99, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ; CHR_TRN tiles $80-$FF
SGB_PKT_PCT:      db $A1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ; PCT_TRN

INCLUDE "sgb_day.inc"
INCLUDE "sgb_night.inc"
